/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.tasks.applications;

import javax.swing.Icon;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class RNAalifoldPanel extends javax.swing.JPanel implements ApplicationPanelInterface {

    SpinnerNumberModel temperatureModel = new SpinnerNumberModel(37, -273, 1000, 0.5);
    SpinnerNumberModel covarianceModel = new SpinnerNumberModel(1, 0, 1000, 0.1);
    SpinnerNumberModel nonCompatiblityModel = new SpinnerNumberModel(1, 0, 1000, 0.1);
    /**
     * Creates new form RNAalifoldPanel
     */
    public RNAalifoldPanel() {
        initComponents();
        
        
        this.temperatureSpinner.setModel(temperatureModel);
        this.covarianceSpinner.setModel(covarianceModel);
        this.nonCompatibilitySpinner.setModel(nonCompatiblityModel);
    }
    
     public String getArgumentString()
    {
        String arguments = "";
        arguments += "-cv "+covarianceSpinner.getValue()+ " -nc "+nonCompatibilitySpinner.getValue() + " -T "+temperatureSpinner.getValue();
        if(this.circularRadioButton.isSelected())
        {
            arguments += " -circ ";
        }
        if(!this.partionFunctionCheckBox.isSelected())
        {
            arguments += " -p0 ";
        }
        return arguments;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conformationGroup = new javax.swing.ButtonGroup();
        partionFunctionCheckBox = new javax.swing.JCheckBox();
        circularRadioButton = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nonCompatibilitySpinner = new javax.swing.JSpinner();
        covarianceSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        temperatureSpinner = new javax.swing.JSpinner();

        partionFunctionCheckBox.setSelected(true);
        partionFunctionCheckBox.setText("Generate base-pairing probability matrix (calculate partition function)");

        conformationGroup.add(circularRadioButton);
        circularRadioButton.setText("Circular");

        conformationGroup.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Linear");

        jLabel4.setText("Conformation");

        jLabel3.setText("Non-compatibility weighting");

        jLabel2.setText("Covariance weighting");

        jLabel1.setText("Temperature");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(partionFunctionCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(circularRadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nonCompatibilitySpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(covarianceSpinner)
                                .addComponent(temperatureSpinner)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(temperatureSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(covarianceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nonCompatibilitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1)
                    .addComponent(circularRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(partionFunctionCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton circularRadioButton;
    private javax.swing.ButtonGroup conformationGroup;
    private javax.swing.JSpinner covarianceSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSpinner nonCompatibilitySpinner;
    private javax.swing.JCheckBox partionFunctionCheckBox;
    private javax.swing.JSpinner temperatureSpinner;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setupApplication(Application application) {
         if(application instanceof RNAalifoldApplication)
        {
            RNAalifoldApplication app = (RNAalifoldApplication)application;
            app.setArguments(getArgumentString());
        } 
    }
    
    @Override
    public String getTitle() {
        return "RNAalifold parameters";
    }

    @Override
    public Icon getIcon() {
        return null;
    }
}
