/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.ui;

import java.awt.BorderLayout;
import nava.tasks.applications.ApplicationController;
import nava.data.types.TabularField;
import nava.ui.navigator.NavigationEvent;
import nava.ui.navigator.NavigationListener;
import nava.ui.navigator.NavigatorPanel;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class DataPanel extends javax.swing.JPanel implements NavigationListener {

    ProjectController projectController;
    ApplicationController appController;
    NavigatorPanel navigatorPanel;
    DataInspectorPanel dataInspectorPanel;
    ApplicationPanel applicationPanel;
    TaskPanel taskPanel;

    /**
     * Creates new form DataPanel
     */
    public DataPanel(ProjectController projectController, ApplicationController appController) {
        initComponents();

        this.projectController = projectController;
        this.appController = appController;

        navigatorPanel = new NavigatorPanel(projectController);
        navigatorPanel.addNavigationListener(this);
        dataInspectorPanel = new DataInspectorPanel(projectController);
        applicationPanel = new ApplicationPanel(appController, projectController);
        taskPanel = new TaskPanel();

        this.jPanel1.add(navigatorPanel, BorderLayout.CENTER);
        this.jPanel2.add(applicationPanel, BorderLayout.CENTER);
        this.jPanel3.add(dataInspectorPanel, BorderLayout.CENTER);
        this.jPanel4.add(taskPanel, BorderLayout.CENTER);
        
        MainFrame.progressBarMonitor.addJProgressBar(jProgressBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        jLabel4 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jProgressBar = new javax.swing.JProgressBar();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tasks"));
        jPanel4.setPreferredSize(new java.awt.Dimension(12, 150));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 3, 1));

        jLabel4.setText("Status");

        jProgressBar.setPreferredSize(new java.awt.Dimension(146, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(694, 694, 694)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 20, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setDividerSize(3);

        jSplitPane1.setDividerLocation(350);
        jSplitPane1.setDividerSize(3);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data inspector"));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 23));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(jPanel2);

        jSplitPane2.setRightComponent(jSplitPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Project navigation"));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 23));
        jPanel1.setName("");
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jSplitPane2.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dataSourceSelectionChanged(NavigationEvent e) {
        applicationPanel.showUsableApplications(e.selectedDataSources);
        if(e.selectedDataSources.size() == 1)
        {
            dataInspectorPanel.updatePanel(e.selectedDataSources.get(0));
        }
        
        for (int i = 0; i < e.selectedDataSources.size(); i++) {
            if (e.selectedDataSources.get(i) instanceof TabularField) {
                //System.out.println(((TabularField) e.selectedDataSources.get(i)).getObject().values);
            }
        }
    }
}
