/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.ui;

import java.awt.BorderLayout;
import nava.tasks.applications.ApplicationController;
import nava.data.types.TabularField;
import nava.ui.navigator.NavigationEvent;
import nava.ui.navigator.NavigationListener;
import nava.ui.navigator.NavigatorPanel;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class DataPanel extends javax.swing.JPanel implements NavigationListener {

    ProjectController projectController;
    ApplicationController appController;
    NavigatorPanel navigatorPanel;
    DataInspectorPanel dataInspectorPanel;
    ApplicationPanel applicationPanel;
    TaskPanel taskPanel;

    /**
     * Creates new form DataPanel
     */
    public DataPanel(ProjectController projectController, ApplicationController appController) {
        initComponents();

        this.projectController = projectController;
        this.appController = appController;

        navigatorPanel = new NavigatorPanel(projectController);
        navigatorPanel.addNavigationListener(this);
        dataInspectorPanel = new DataInspectorPanel(projectController);
        applicationPanel = new ApplicationPanel(appController, projectController);
        taskPanel = new TaskPanel();

        this.jPanel1.add(navigatorPanel, BorderLayout.CENTER);
        this.jPanel2.add(applicationPanel, BorderLayout.CENTER);
        this.jPanel3.add(dataInspectorPanel, BorderLayout.CENTER);
        this.jPanel4.add(taskPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigation"));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data inspector"));
        jPanel3.setMinimumSize(new java.awt.Dimension(350, 23));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 23));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tasks"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dataSourceSelectionChanged(NavigationEvent e) {
        applicationPanel.showUsableApplications(e.selectedDataSources);
        if(e.selectedDataSources.size() == 1)
        {
            dataInspectorPanel.updatePanel(e.selectedDataSources.get(0));
        }
        
        for (int i = 0; i < e.selectedDataSources.size(); i++) {
            if (e.selectedDataSources.get(i) instanceof TabularField) {
                //System.out.println(((TabularField) e.selectedDataSources.get(i)).getObject().values);
            }
        }
    }
}
