/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.ui;

import javax.swing.DefaultListModel;
import nava.tasks.AnnotationMappingTask;
import nava.tasks.MappingTask;
import nava.tasks.Task;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class TaskPanel extends javax.swing.JPanel {

    
    
    /**
     * Creates new form TaskPanel
     */
    public TaskPanel() {
        initComponents();
       /* TaskListCellRenderer taskListCellRenderer = new TaskListCellRenderer();
        DefaultListModel<Task> taskListModel = new DefaultListModel<Task>();
        
        jList1.setCellRenderer(taskListCellRenderer);
        jList1.setModel(taskListModel);
        
        taskListModel.addElement(new AnnotationMappingTask(null,null,null, null));
        taskListModel.addElement(new MappingTask(null,null,null));*/
        
        add(new TaskTable(MainFrame.taskManager));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
