/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.ui;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import nava.analyses.ApplicationTask;
import nava.tasks.Task;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class TaskPanel extends javax.swing.JPanel implements ListSelectionListener {

    TaskTable taskTable;
    TaskConsolePanel taskConsolePanel;

    /**
     * Creates new form TaskPanel
     */
    public TaskPanel() {
        initComponents();
        /*
         * TaskListCellRenderer taskListCellRenderer = new
         * TaskListCellRenderer(); DefaultListModel<Task> taskListModel = new
         * DefaultListModel<Task>();
         *
         * jList1.setCellRenderer(taskListCellRenderer);
         * jList1.setModel(taskListModel);
         *
         * taskListModel.addElement(new AnnotationMappingTask(null,null,null,
         * null)); taskListModel.addElement(new MappingTask(null,null,null));
         */
        taskTable = new TaskTable(MainFrame.taskManager);
        taskTable.table.getSelectionModel().addListSelectionListener(this);
        jSplitPane1.setDividerLocation(0.6);
        jSplitPane1.setResizeWeight(0.3);
        jSplitPane1.setLeftComponent(taskTable);

        taskConsolePanel = new TaskConsolePanel();
        jSplitPane1.setRightComponent(taskConsolePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(500);
        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        int selectedRow = taskTable.table.getSelectedRow();
        //Task selectedTask = (Task) taskTable.tableDataModel.getValueAt(selectedRow, 4);
        if (selectedRow > -1) {
            Task selectedTask = (Task) taskTable.table.getValueAt(selectedRow, 4);
            if (selectedTask instanceof ApplicationTask) {
                taskConsolePanel.setApplicationTask((ApplicationTask) selectedTask);
            } else {
                taskConsolePanel.errorConsolePanel.clearScreen();
                taskConsolePanel.standardConsolePanel.clearScreen();
            }
        } else {
            taskConsolePanel.errorConsolePanel.clearScreen();
            taskConsolePanel.standardConsolePanel.clearScreen();
        }
    }
}
