/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.structurevis;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import nava.data.types.Alignment;
import nava.data.types.DataSource;
import nava.data.types.Tabular;
import nava.data.types.TabularField;
import nava.structurevis.data.NucleotideComposition;
import nava.ui.ProjectModel;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class NucleotideCompositionPanel extends javax.swing.JPanel {

    ProjectModel projectModel;
    DefaultComboBoxModel<Alignment> nucleotideAlignmentComboBoxModel = new DefaultComboBoxModel<>();
    Alignment selectedAlignment;
    
    /**
     * Creates new form NucleotideCompositionPanel
     */
    public NucleotideCompositionPanel(ProjectModel projectModel) {
        initComponents();
        this.projectModel = projectModel;

        this.nucleotideAlignmentComboBox.setModel(nucleotideAlignmentComboBoxModel);
        
        populateNucleotideAlignmentComboBox(Collections.list(projectModel.dataSources.elements()));
    }

    public void populateNucleotideAlignmentComboBox(List<DataSource> dataSources) {
        //Alignment alignment = (Alignment) nucleotideAlignmentComboBox.getSelectedItem();

        nucleotideAlignmentComboBoxModel.removeAllElements();
        for (DataSource dataSource : dataSources) {
            if (dataSource instanceof Alignment) {
                Alignment al = (Alignment) dataSource;
                if (al.type == Alignment.Type.NUCLEOTIDE || al.type == Alignment.Type.CODING) {
                    nucleotideAlignmentComboBoxModel.addElement(al);
                }
            }
        }
    }

    public NucleotideComposition getNucleotideSource() {
        selectedAlignment = (Alignment) nucleotideAlignmentComboBoxModel.getSelectedItem();
        if(selectedAlignment != null)
        {
            NucleotideComposition nuc = new NucleotideComposition(selectedAlignment);
            nuc.title = selectedAlignment.title;
            return nuc;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nucleotideAlignmentComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Select nucleotide source");

        nucleotideAlignmentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Add from file");

        jLabel2.setText("or");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nucleotideAlignmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nucleotideAlignmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox nucleotideAlignmentComboBox;
    // End of variables declaration//GEN-END:variables


}
