/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.structurevis;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import nava.data.types.Alignment;
import nava.data.types.DataSource;
import nava.data.types.SecondaryStructure;
import nava.data.types.SecondaryStructureData;
import nava.structurevis.data.MappingSource;
import nava.structurevis.data.StructureSource;
import nava.ui.MainFrame;
import nava.ui.ProjectController;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class StructurePanel extends javax.swing.JPanel implements ItemListener {

    DefaultComboBoxModel<SecondaryStructure> structureComboBoxModel = new DefaultComboBoxModel<>();
    
    StructureVisController structureVisController;
    ProjectController projectController;
    
    public StructureDrawPanel structureDrawPanel;

    /**
     * Creates new form StructurePanel
     */
    public StructurePanel(StructureVisController structureVisController, ProjectController projectController) {
        initComponents();
        this.structureVisController = structureVisController;
        this.projectController = projectController;

        structureDrawPanel = new StructureDrawPanel(structureVisController);
        topScrollPane.setViewportView(structureDrawPanel);

        structureComboBox.setModel(structureComboBoxModel);
        structureComboBox.addItemListener(this);
        
        populateStructureComboBox(Collections.list(projectController.projectModel.dataSources.elements()));
    }
    
    
    
    public void populateStructureComboBox(List<DataSource> dataSources)
    {
        structureComboBoxModel.removeAllElements();
        //mappingSourceComboBoxModel.removeAllElements();
        for(DataSource dataSource : dataSources)
        {
            if(dataSource instanceof SecondaryStructure)
            {
                structureComboBoxModel.addElement((SecondaryStructure)dataSource);
            }
            if(dataSource instanceof Alignment)
            {
                // mappingSourceComboBoxModel.addElement((Alignment)dataSource);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        topScrollPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        structureComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        topPanel.setLayout(new java.awt.BorderLayout());
        topPanel.add(topScrollPane, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Structure");
        jPanel2.add(jLabel1);

        structureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(structureComboBox);

        jButton1.setText("Edit mapping source");
        jPanel2.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox structureComboBox;
    private javax.swing.JPanel topPanel;
    private javax.swing.JScrollPane topScrollPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        SecondaryStructure s = (SecondaryStructure) structureComboBox.getSelectedItem();
        if(s != null)
        {
            SecondaryStructureData d = s.getObject(MainFrame.dataSourceCache);        
            structureDrawPanel.setStructure(d.pairedSites, 0, d.pairedSites.length);
            MappingSource mappingSource = new MappingSource();
            mappingSource.sequence = d.sequence;
            if(mappingSource != null)
            {
                structureVisController.addStructureSource(new StructureSource(s, mappingSource));
            }
        }
    }
}
