/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.structurevis;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import nava.data.types.Alignment;
import nava.data.types.DataSource;
import nava.data.types.SecondaryStructure;
import nava.data.types.SecondaryStructureData;
import nava.structurevis.data.MappingSource;
import nava.structurevis.data.StructureSource;
import nava.structurevis.data.Substructure;
import nava.ui.MainFrame;
import nava.ui.ProjectController;
import nava.utils.ComboBoxItem;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class SubstructurePanel extends javax.swing.JPanel implements ItemListener {

    DefaultComboBoxModel<SecondaryStructure> structureComboBoxModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<ComboBoxItem> substructureComboBoxModel = new DefaultComboBoxModel<>();
    StructureVisController structureVisController;
    ProjectController projectController;
    SubstructureModel substructureModel = new SubstructureModel();
    public SubstructureDrawPanel structureDrawPanel;
    

    /**
     * Creates new form StructurePanel
     */
    public SubstructurePanel(StructureVisController structureVisController, ProjectController projectController) {
        initComponents();
        this.structureVisController = structureVisController;
        this.projectController = projectController;

        structureDrawPanel = new SubstructureDrawPanel(substructureModel);
        topScrollPane.setViewportView(structureDrawPanel);

        structureComboBox.setModel(structureComboBoxModel);
        structureComboBox.addItemListener(this);

        substructureComboBox.setModel(substructureComboBoxModel);
        substructureComboBox.addItemListener(this);

        populateStructureComboBox(Collections.list(projectController.projectModel.dataSources.elements()));
    }

    public void populateStructureComboBox(List<DataSource> dataSources) {
        structureComboBoxModel.removeAllElements();
        //mappingSourceComboBoxModel.removeAllElements();
        for (DataSource dataSource : dataSources) {
            if (dataSource instanceof SecondaryStructure) {
                structureComboBoxModel.addElement((SecondaryStructure) dataSource);
            }
            if (dataSource instanceof Alignment) {
                // mappingSourceComboBoxModel.addElement((Alignment)dataSource);
            }
        }
    }

    public void populateSubtructureComboBox() {
        substructureComboBoxModel.removeAllElements();
        ArrayList<Substructure> list = substructureModel.getSubstructures();
        for (int i = 0; i < list.size(); i++) {
            ComboBoxItem<Substructure> item = new ComboBoxItem<>(list.get(i), i + "");
            substructureComboBoxModel.addElement(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        topScrollPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        structureComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        substructureComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        topPanel.setLayout(new java.awt.BorderLayout());
        topPanel.add(topScrollPane, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Structure");
        jPanel2.add(jLabel1);

        structureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(structureComboBox);

        jLabel2.setText("Substructure");
        jPanel2.add(jLabel2);

        substructureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(substructureComboBox);

        jButton1.setText("Add structure");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StructureDataDialog d = new StructureDataDialog(null, true, projectController.projectModel, structureVisController);
        d.setSize(640, 480);
        d.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox structureComboBox;
    private javax.swing.JComboBox substructureComboBox;
    private javax.swing.JPanel topPanel;
    private javax.swing.JScrollPane topScrollPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource().equals(structureComboBox)) {
            SecondaryStructure s = (SecondaryStructure) structureComboBox.getSelectedItem();
            if (s != null) {
                MappingSource mappingSource = new MappingSource(s.getObject(MainFrame.dataSourceCache).sequence);
                StructureSource structureSource = new StructureSource(s, mappingSource);
                //
                if (mappingSource != null) {
                    structureVisController.addStructureSource(structureSource);
                    structureSource.loadData();
                    substructureModel.setStructureSource(structureSource);
                    structureDrawPanel.openSubstructure(structureSource.substructures.get(0));
                    populateSubtructureComboBox();
                }
            }
        } else if (e.getSource().equals(substructureComboBox)) {
            ComboBoxItem<Substructure> comboBoxItem = (ComboBoxItem<Substructure>) substructureComboBoxModel.getSelectedItem();
            if (comboBoxItem != null) {
                structureDrawPanel.openSubstructure(comboBoxItem.getObject());
            }
        }
    }
}
