/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.structurevis;

import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import nava.data.types.Alignment;
import nava.data.types.DataSource;
import nava.data.types.SecondaryStructure;
import nava.data.types.SecondaryStructureData;
import nava.structurevis.data.*;
import nava.structurevis.navigator.DataOverlayTreePanel;
import nava.ui.MainFrame;
import nava.ui.ProjectController;
import nava.ui.ProjectModel;
import nava.utils.CustomItem;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class SubstructurePanel extends javax.swing.JPanel implements ChangeListener, ItemListener, ListDataListener, SubstructureModelListener, StructureVisView {

    DefaultComboBoxModel<StructureSource> structureComboBoxModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<CustomItem> substructureComboBoxModel = new DefaultComboBoxModel<>();
    StructureVisController structureVisController;
    ProjectController projectController;
    public SubstructureDrawPanel structureDrawPanel;
    DataLegend dataLegend1D = new DataLegend();
    DataLegend dataLegend2D = new DataLegend();

    /**
     * Creates new form StructurePanel
     */
    public SubstructurePanel(StructureVisController structureVisController, ProjectController projectController) {
        initComponents();
        this.structureVisController = structureVisController;
        this.projectController = projectController;

        structureDrawPanel = new SubstructureDrawPanel(structureVisController.structureVisModel.substructureModel);
        structureVisController.structureVisModel.substructureModel.addSubstructureModelListener(this);
        topScrollPane.setViewportView(structureDrawPanel);

        structureComboBox.setModel(structureComboBoxModel);
        structureComboBox.addItemListener(this);

        substructureComboBox.setModel(substructureComboBoxModel);
        substructureComboBox.addItemListener(this);

        structureVisController.addView(this);
//        structureVisController.structureSources.addListDataListener(this);

        treePanel.add(new DataOverlayTreePanel(projectController,structureVisController), BorderLayout.CENTER);

        dataLegend1D.addChangeListener(this);
        dataLegend2D.addChangeListener(this);
        legendPanel.add(dataLegend1D);
        legendPanel.add(dataLegend2D);


        //populateStructureComboBox(Collections.list(projectController.projectModel.dataSources.elements()));
    }

    public void refresh() {
        this.populateStructureSourceComboBox();
        this.populateSubtructureComboBox();
        // TODO remember which structures/substructures were selected previously
    }

    /*
     * public void populateStructureComboBox(List<DataSource> dataSources) {
     * structureComboBoxModel.removeAllElements();
     * //mappingSourceComboBoxModel.removeAllElements(); for (DataSource
     * dataSource : dataSources) { if (dataSource instanceof SecondaryStructure)
     * { structureComboBoxModel.addElement((SecondaryStructure) dataSource); }
     * if (dataSource instanceof Alignment) { //
     * mappingSourceComboBoxModel.addElement((Alignment)dataSource); } } }
     */
    public void populateSubtructureComboBox() {
        substructureComboBoxModel.removeAllElements();
        ArrayList<Substructure> list = structureVisController.structureVisModel.substructureModel.getSubstructures();
        for (int i = 0; i < list.size(); i++) {
            CustomItem<Substructure> item = new CustomItem<>(list.get(i), i + "");
            substructureComboBoxModel.addElement(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        topScrollPane = new javax.swing.JScrollPane();
        legendPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        treePanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        structureComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        substructureComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(150);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        topScrollPane.setMinimumSize(new java.awt.Dimension(40, 23));
        topScrollPane.setPreferredSize(new java.awt.Dimension(500, 2));
        jPanel4.add(topScrollPane);

        legendPanel.setMaximumSize(new java.awt.Dimension(300, 32767));
        legendPanel.setPreferredSize(new java.awt.Dimension(150, 289));
        legendPanel.setLayout(new javax.swing.BoxLayout(legendPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel4.add(legendPanel);

        jSplitPane1.setRightComponent(jPanel4);

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 319));

        treePanel.setLayout(new java.awt.BorderLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/add-16x16.png"))); // NOI18N
        jButton2.setText("Add data overlay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(treePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(treePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Structure");
        jPanel2.add(jLabel1);

        structureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(structureComboBox);

        jLabel2.setText("Substructure");
        jPanel2.add(jLabel2);

        substructureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(substructureComboBox);

        jButton1.setText("Add structure");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StructureDataDialog d = new StructureDataDialog(null, true, projectController.projectModel, structureVisController);
        d.setSize(640, 580);
        d.setEditMode(false);
        d.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddDataOverlayDialog dialog = new AddDataOverlayDialog(null, true, projectController, structureVisController);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel legendPanel;
    private javax.swing.JComboBox structureComboBox;
    private javax.swing.JComboBox substructureComboBox;
    private javax.swing.JScrollPane topScrollPane;
    private javax.swing.JPanel treePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource().equals(structureComboBox)) {
            StructureSource structureSource = (StructureSource) structureComboBox.getSelectedItem();

            if (structureSource != null && structureSource.mappingSource != null) {
                structureVisController.structureVisModel.substructureModel.setStructureSource(structureSource);
            }

            /*
             * if (structureSource != null && structureSource.mappingSource !=
             * null) {
             * //structureVisController.addStructureSource(structureSource);
             * structureSource.loadData();
             * structureVisController.substructureModel.setStructureSource(structureSource);
             * if (structureSource.substructures.size() > 0) {
             * structureDrawPanel.openSubstructure(structureSource.substructures.get(0));
             * } populateSubtructureComboBox();
            }
             */
        } else if (e.getSource().equals(substructureComboBox)) {
            CustomItem<Substructure> comboBoxItem = (CustomItem<Substructure>) substructureComboBoxModel.getSelectedItem();
            if (comboBoxItem != null) {
                structureDrawPanel.openSubstructure(comboBoxItem.getObject());
            }
        }
    }

    public void populateStructureSourceComboBox() {
        structureComboBoxModel.removeAllElements();
        ArrayList<StructureSource> list = structureVisController.structureVisModel.structureSources.getArrayListShallowCopy();
        for (int i = 0; i < list.size(); i++) {
            //ComboBoxItem<StructureSource> item = new ComboBoxItem<>(list.get(i), list.get(i).structure.toString());
            structureComboBoxModel.addElement(list.get(i));
        }
    }

    @Override
    public void intervalAdded(ListDataEvent e) {
        //populateStructureSourceComboBox();
    }

    @Override
    public void intervalRemoved(ListDataEvent e) {
       // populateStructureSourceComboBox();
    }

    @Override
    public void contentsChanged(ListDataEvent e) {
       // populateStructureSourceComboBox();
    }

    @Override
    public void dataSource1DChanged(DataOverlay1D dataSource1D) {
        if (dataSource1D == null) {
            dataLegend1D.setVisible(false);
        } else {
            dataLegend1D.setVisible(true);
            dataLegend1D.setLegend(dataSource1D.title, dataSource1D.dataTransform, dataSource1D.colorGradient, dataSource1D.defaultColorGradient);
        }
        structureDrawPanel.redraw();
    }

    @Override
    public void dataSource2DChanged(DataOverlay2D dataSource2D) {
        if (dataSource2D == null) {
            dataLegend2D.setVisible(false);
        } else {
            dataLegend2D.setVisible(true);
            dataLegend2D.setLegend(dataSource2D.title, dataSource2D.dataTransform, dataSource2D.colorGradient, dataSource2D.defaultColorGradient);
        }

        structureDrawPanel.redraw();
    }

    @Override
    public void structureSourceChanged(StructureSource structureSource) {
        if (structureSource != null && structureSource.mappingSource != null) {
            //structureVisController.addStructureSource(structureSource);
            structureSource.loadData();
            if (structureSource.substructures.size() > 0) {
                System.out.println(structureSource.substructures.get(0));
                structureDrawPanel.openSubstructure(structureSource.substructures.get(0));
            }
            populateSubtructureComboBox();
        }
        else
        {
            structureDrawPanel.openSubstructure(null);
        }
        structureDrawPanel.redraw();
    }

    @Override
    public void annotationSourceChanged(AnnotationSource annotationSource) {
        structureDrawPanel.redraw();
    }

    @Override
    public void nucleotideSourceChanged(NucleotideComposition nucleotideSource) {        
        structureDrawPanel.redraw();
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        if (e.getSource().equals(dataLegend1D) || e.getSource().equals(dataLegend2D)) {            
            structureDrawPanel.model.thresholdMin1D = dataLegend1D.getMinValue();
            structureDrawPanel.model.thresholdMax1D = dataLegend1D.getMaxValue();
            structureDrawPanel.model.thresholdMin2D = dataLegend2D.getMinValue();
            structureDrawPanel.model.thresholdMax2D = dataLegend2D.getMaxValue();
            structureDrawPanel.model.useLowerThreshold1D = !dataLegend1D.downSliderOpen;
            structureDrawPanel.model.useUpperThreshold1D = !dataLegend1D.upSliderOpen;
            structureDrawPanel.model.useLowerThreshold2D = !dataLegend2D.downSliderOpen;
            structureDrawPanel.model.useUpperThreshold2D = !dataLegend2D.upSliderOpen;
            structureDrawPanel.redraw();
        }
    }

    @Override
    public void dataOverlayAdded(Overlay overlay) {
        populateStructureSourceComboBox();
    }

    @Override
    public void dataOverlayRemoved(Overlay overlay) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void dataOverlayChanged(Overlay overlay) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }
}
