/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nava.alignment;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Michael Golden <michaelgolden0@gmail.com>
 */
public class SettingsPanel extends javax.swing.JPanel {

    SpinnerNumberModel substructureWindowSpinnerModel = new SpinnerNumberModel(75, 10, Integer.MAX_VALUE, 1);
    SpinnerNumberModel similarityCutoffSpinnerModel = new SpinnerNumberModel(0.75, 0, 1, 0.01);

    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel() {
        initComponents();
        substructureWindowSpinner.setModel(substructureWindowSpinnerModel);
        similarityCutoffSpinner.setModel(similarityCutoffSpinnerModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        substructureWindowGroup = new javax.swing.ButtonGroup();
        substructureWindowSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        relaxedRadioButton = new javax.swing.JRadioButton();
        strictRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        similarityCutoffSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        identifyConservedSubstructuresCheckBox = new javax.swing.JCheckBox();
        methodComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Sliding window size");

        substructureWindowGroup.add(relaxedRadioButton);
        relaxedRadioButton.setSelected(true);
        relaxedRadioButton.setText("Relaxed");

        substructureWindowGroup.add(strictRadioButton);
        strictRadioButton.setText("Strict");

        jLabel2.setText("Substructure window setting");

        jLabel4.setText("Similarity cut-off");

        identifyConservedSubstructuresCheckBox.setText("Identify conserved substructures");

        methodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Method");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(substructureWindowSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(strictRadioButton)
                                    .addComponent(relaxedRadioButton)))
                            .addComponent(identifyConservedSubstructuresCheckBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(similarityCutoffSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(methodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(substructureWindowSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relaxedRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strictRadioButton)
                .addGap(18, 18, 18)
                .addComponent(identifyConservedSubstructuresCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(methodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(similarityCutoffSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox identifyConservedSubstructuresCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JComboBox methodComboBox;
    public javax.swing.JRadioButton relaxedRadioButton;
    public javax.swing.JSpinner similarityCutoffSpinner;
    public javax.swing.JRadioButton strictRadioButton;
    private javax.swing.ButtonGroup substructureWindowGroup;
    public javax.swing.JSpinner substructureWindowSpinner;
    // End of variables declaration//GEN-END:variables
}
